<?php

/**
 * @file
 * Contains chart_block_nodes.module.
 */

use Drupal\charts\Charts\ModuleSelector;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chart_block_nodes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chart_block_nodes module.
    case 'help.page.chart_block_nodes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Created a block using the Charts API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chart_block_nodes_theme() {
  $vars = [
    'library' => '',
    'categories' => '',
    'seriesData' => '',
    'options' => '',
  ];
  return [
    'chart_block_nodes' => [
      'template' => 'chart_block_nodes',
      'variables' => $vars,
    ],
  ];
}

/**
 * Implements template_preprocess_page
 *
 * @param $variables
 */
function template_preprocess_chart_block_nodes(&$variables) {
  $plugin_manager = \Drupal::service('plugin.manager.charts');
  $plugin = $plugin_manager->createInstance($variables['library']);
  $plugin->buildVariables($variables['options'], $variables['categories'], $variables['seriesData'], [], $variables, 'xyz');
}